name: app_1
publish_to: 'none'

environment:
  sdk: '^3.8.0'
dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../../packages/shared_ui
  core:
    path: ../../packages/core
  auth_module:
    path: ../../packages/auth_module
  search_module:
    path: ../../packages/search_module
  profile_module:
    path: ../../packages/profile_module